# name: Release and Docker

# on:
#   push:
#     branches: [master, main]
#     paths:
#       - "apps/api/**"

# jobs:
#   release:
#     name: Release & Build Docker
#     runs-on: ubuntu-latest

#     permissions:
#       contents: write
#       packages: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20.8.1

#       - name: Setup pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: latest

#       - name: Install dependencies
#         run: pnpm install --no-frozen-lockfile

#       - name: Run semantic-release
#         id: release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: pnpm dlx semantic-release

#       - name: Extract version
#         id: version
#         run: |
#           VERSION=$(git describe --tags --abbrev=0)
#           echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

#       - name: Build Docker image
#         run: |
#           docker build -t myuser/myapp:${{ steps.version.outputs.VERSION }} .

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Push Docker image
#         run: |
#           docker push myuser/myapp:${{ steps.version.outputs.VERSION }}
